---
title: "Data manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

## Load in the FAS litters DATA
```{r}
litters_df = read_csv("./data/FAS_litters.csv",na = c("NA", ".", ""))
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose some columns and not others
```{r}
select(litters_df, group,litter_number,gd0_weight)
```

```{r}
select(litters_df,group,gd0_weight:gd_of_birth)
# a:b意味着选择从a到b的所有列
```

```{r}
select(litters_df,-litter_number)
#除了那个变量都留下来
```

Renaming columns...
```{r}
select(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)
#rename的同时把这两列挑选出来
```

```{r}
rename(litters_df, GROUP = group, LiTtEr_NuMbEr = litter_number)
#rename的时候保留整个表格
```

Select helpers
```{r}
select(litters_df,starts_with("gd"))
#筛选出以gd开头的变量
```

Relocate
```{r}
select(litters_df, litter_number, everything())
#把litternumkber放到第一个，其他的保留
```

```{r}
relocate(litters_df, litter_number)
# 达成同上的效果
```

## `filter`

```{r}
filter(litters_df,gd0_weight < 22)
#选出gd0——weght小于22的所有变量
```

```{r}
filter(litters_df,gd0_weight >= 22)
```

```{r}
filter(litters_df,gd_of_birth == 20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20))
```

```{r}
filter(litters_df, gd_of_birth != 20)
```

```{r}
filter(litters_df,gd0_weight >= 22, gd_of_birth == 20)
#同时满足两个条件
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Mod8","Con7"))
#group是mod8或者是con7的都保留
```


## `mutate`

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
#可以创造一个新的变量wt_gain = gd18_weight - gd0_weight，还可以进行计算
```

## `arrange`

```{r}
arrange(litters_df,pups_born_alive)
```

```{r}
arrange(litters_df,pups_born_alive,gd0_weight)
```

## `/>`

```{r}
litters_df_raw = read_csv("./data/FAS_litters.csv", na = c("NA", ".", ""))
litters_df_clean_names = janitor::clean_names(litters_df_raw)
litters_df_selected_cols = select(litters_df_clean_names, -pups_survive)
litters_mutated = mutate(litters_df_selected_cols, wt_gain = gd18_weight - gd0_weight, group = str_to_lower(group))
litters_df_with_vars_without_missing = 
  drop_na(litters_mutated, wt_gain)
```

if you use the pipes!
```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |> select(-pups_survive) |>
  mutate(wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) |>
  drop_na(wt_gain)
```









